version: "3"

services:

  generate-web:
    tty: true
    stdin_open: true
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    image: ghcr.io/jinyoung/gpt-engineer:v5
#    command: ["-sh"]
    volumes:
      - ../web:/project
  generate-payment:
    tty: true
    stdin_open: true
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    image: ghcr.io/jinyoung/gpt-engineer:v5
#    command: ["-sh"]
    volumes:
      - ../payment:/project
  generate-delivery:
    tty: true
    stdin_open: true
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    image: ghcr.io/jinyoung/gpt-engineer:v5
#    command: ["-sh"]
    volumes:
      - ../delivery:/project
  generate-membership:
    tty: true
    stdin_open: true
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    image: ghcr.io/jinyoung/gpt-engineer:v5
#    command: ["-sh"]
    volumes:
      - ../membership:/project
